name: Select Latest Semver
description: Consumes a JSON array of SemVer strings, and returns the version that is the latest. Strings with invalid SemVer versions are ignored.
runs:
  using: node16
  main: dist/index.js
inputs:
  list:
    description: Array of SemVer strings to process
    required: true
    default: '[]'
  fail-on-empty:
    description: Indicates if the action should fail if no valid SemVer versions can be selected. If set to false, the value latest will be an empty string when no valid SemVer values can be selected.
    required: false
    default: 'true'
outputs:
  latest:
    description: The latest SemVer version found in 'list'.
