name: Select Latest Semver
description: Consumes a JSON array of SemVer strings, and returns the version that is the latest. Strings with invalid SemVer versions are ignored.
runs:
  using: node16
  main: dist/index.js
inputs:
  list:
    description: Array of SemVer strings to process
    required: true
    default: '[]'
  fail-on-empty:
    description: Indicates if the action should fail if no valid SemVer versions can be selected. If set to false, the value latest will be an empty string when no valid SemVer values can be selected.
    required: false
    default: 'true'
  coercion:
    description: Indicates if the semantic version coercion should be performed on the input values, this allows non-standard values such as `1` and `1.0` to be accepted as `1.0.0`.
    required: false
    default: 'false'
  strict-parsing:
    description: Indicates if the action should interprete version strings strictly.
    required: false
    default: 'true'
  strict-output:
    description: Indicates if the value returned by latest will be the original input value or converted to strictly compliant SemVer format. This flag is only useful when strict-parsing is disabled.
    required: false
    default: 'true'
outputs:
  latest:
    description: The latest SemVer version found in 'list'.
